include:
- ./func/*
kind: ArchiveUploadSpec
name: func-9iPN

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: user-review-fn-730c2b1e-c415-46ba-9900-eb856df59877
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: user-review-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-9iPN
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-19T20:21:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: user-review-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: user-review-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_user_review_data
    packageref:
      name: user-review-fn-730c2b1e-c415-46ba-9900-eb856df59877
      namespace: default
  requestsPerPod: 1
  resources: {}
