include:
- ./func/*
kind: ArchiveUploadSpec
name: func-X5PP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: user-review-fn-9068bbaa-be8d-4ef6-9c2b-fcb61c0b0d36
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: user-review-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-X5PP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-19T20:21:44Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: user-review-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 10
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: user-review-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_user_review_data
    packageref:
      name: user-review-fn-9068bbaa-be8d-4ef6-9c2b-fcb61c0b0d36
      namespace: default
  requestsPerPod: 1
  resources: {}
