global:
  application: fission-onboarding-br-put-review
  namespace: develop

  image:
    repository: "nexus.inf-lionx.com.br"
    pullPolicy: Always
    pullSecret: nexus-v3

  labels:
    external: false
    kafka: true
    mongo: true
    priority: 5

  serviceaccount:
    enabled: false
    annotations: []

  configMap:
    enabled: false
    data: {}

  revisionHistoryLimit: 4

  annotations:
    sidecar.istio.io/inject: "false"    

  nameOverride: ""
  fullnameOverride: ""

  volumes:
    enabled: false
    name:
    hostPath:

  nodeAffinity:
    bff: true

initcontainer: 
  enabled: true

restartPolicy: Always

deployment:
  - name: fission-onboarding-br-put-review
    enabled: true
    containers:    
    - name: fission-onboarding-br-put-review
      tag: 0.3.0
      imagename: fission-onboarding-br-put-review
      containerPorts: 8888

      probes:
        enabled: false
      
      env: {}

      resources:
        requests:
          cpu: 128m
          memory: 128Mi
        limits:
          cpu: 256m
          memory: 256Mi

      hpa:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
        metrics:
          cpu: 80
          memory: 80

      service:
        enabled: true
        name: http
        protocol: TCP
        annotations: []

      ingress:
        enabled: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        className: kong
        path: /